"""added models: SocialNetwork, OurMission

Revision ID: 41b43265cfb2
Revises: 99152597bb74
Create Date: 2025-11-16 18:55:50.799801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b43265cfb2'
down_revision: Union[str, Sequence[str], None] = '99152597bb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ourmissions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Asia/Bishkek', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Asia/Bishkek', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socialnetworks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Asia/Bishkek', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('Asia/Bishkek', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialnetworks')
    op.drop_table('ourmissions')
    # ### end Alembic commands ###
