"""Fixed bug in model Characteristics and Category

Revision ID: b0b6ae9bdf0b
Revises: 379c6c5318c7
Create Date: 2025-11-08 19:59:33.852389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b6ae9bdf0b'
down_revision: Union[str, Sequence[str], None] = '379c6c5318c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristicses', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'characteristicses', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characteristicses', type_='foreignkey')
    op.drop_column('characteristicses', 'product_id')
    # ### end Alembic commands ###
