"""added icon field for the category and brand

Revision ID: e3246e879aa5
Revises: f1ec633063f1
Create Date: 2025-11-14 13:50:15.624091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3246e879aa5'
down_revision: Union[str, Sequence[str], None] = 'f1ec633063f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    op.drop_column('brands', 'icon')
    # ### end Alembic commands ###
